### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by millysecurity** [NathanDuma/LinkedIn-Easy-Apply-Bot#1]
Getting the following error when running `python main.py`

```
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    parameters = validate_yaml()
  File "main.py", line 73, in validate_yaml
    assert len(parameters['positions']) > 0
TypeError: object of type 'NoneType' has no len()

```

Using python 3.7.7

**Comment by soychristophe** [comment]
@millysecurity  Sorry, how did you fix the error? thanks

**Comment by balayokesh** [comment]
you need to change the placeholder text for positions at line 32 of `config.yaml` file

![image](https://user-images.githubusercontent.com/59578892/185764932-07dcd13e-8735-456d-9679-1c3b37fce2a3.png)

**Comment by balayokesh** [comment]
> you need to change the placeholder text for positions at line 32 of `config.yaml` file

![image](https://user-images.githubusercontent.com/59578892/185764962-9091428e-66bc-4476-bf52-6e76390b5e7d.png)
