### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by ob312** [NathanDuma/LinkedIn-Easy-Apply-Bot#11]
hi, 

I am receiving the error below - sorry no coding experience of any sort. Could you help?

PS C:\Users\XXX\Documents\LinkedIn-Easy-Apply-Bot-master> python3 main.py
Traceback (most recent call last):
  File "C:\Users\XXX\Documents\LinkedIn-Easy-Apply-Bot-master\main.py", line 122, in <module>
    parameters = validate_yaml()
  File "C:\Users\XXX\Documents\LinkedIn-Easy-Apply-Bot-master\main.py", line 40, in validate_yaml
    assert len(parameters['password']) > 0
TypeError: object of type 'int' has no len()

Thank you!

**Comment by NathanDuma** [comment]
It is because your password is just numbers. When the yaml file gets read, it thinks your password is a number, not a string. You can fix this in 2 ways:
1. Add quotation marks around your password in the yaml file, or
2. change the parameters['password'] to ''.format(parameters['password'])

**Comment by ob312** [comment]
It worked amazing, thanks! Any solution to prevent the code from overwriting the previously filled info? 

What is the best way to add custom questions and answers? Is it possible to have the code gather and log them so we can review and add them?

**Comment by ob312** [comment]
For example: “are you comfortable working in a remote setting?”

**Comment by ob312** [comment]
Or “ I certify that all of the information furnished on this
application and during the application process is true,
complete and correct to the best of my knowledge. I
understand that any misrepresentation or omission of
facts called for may result in refusal to hire or, if hired,
may result in my dismissal at any time regardless of when
the false answer or omissions are discovered” etc as yes/no box

**Comment by NathanDuma** [comment]
How often are you seeing those questions? My bot only covers the standard linkedin questions that the recruiter can choose from when making a job posting. It does not cover custom questions, or any questions that are given through a third party recruiting site (like zip recruiter). 

My bot will try to answer those questions regardless, even though it may not be the most correct answer.

**Comment by ob312** [comment]
Appreciate the response! Solved the problem.

Sorry for hounding here - but i guess i turned out to be a power user of the bot. Any ideas on the error below?

[22336:28544:1129/212913.571:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is
Applying to the job....
C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webelement.py:340: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

Best,

**Comment by ob312** [comment]
also these:

[34760:19312:1129/213856.123:ERROR:device_event_log_impl.cc(214)] [21:38:56.119] USB: usb_service_win.cc:261 Failed to get device driver name: Element not found. (0x490)
[34760:19312:1129/213856.137:ERROR:device_event_log_impl.cc(214)] [21:38:56.133] USB: usb_service_win.cc:284 SetupDiEnumDeviceInterfaces: No more data is available. (0x103)

**Comment by NathanDuma** [comment]
Ignore those, they are no related to my bot. They are harmless.

**Comment by ob312** [comment]
Thanks. one last thing;  any chance to apply "job function" filter

Best

**Comment by NathanDuma** [comment]
No plans currently. It looks like they added the on-site/hybrid options as well. Its not hard to add to the config, add validation, and add the relevant URL information. Feel free to make a PR with it and I can merge.

**Comment by ob312** [comment]
Well i am not qualifies enough but thanks - i will see if i can anyway :)
