### ISSUE TITLE
Jobs apps are "failed" but are showing as applied on LinkedIn

### ISSUE THREAD

**Issue by hemenge133** [NathanDuma/LinkedIn-Easy-Apply-Bot#12]
Just hoping this doesn't have any antilock implications really.

OS: Win11
Python: 3.10
`Failed to apply to job! Please submit a bug report with this link: https://www.linkedin.com/jobs/view/2829318904/`

**Comment by hemenge133** [comment]
`Failed to apply to job! Please submit a bug report with this link: https://www.linkedin.com/jobs/view/2829318904/`

**Comment by NathanDuma** [comment]
Is this for every job you apply to? I got this sometimes, and restarting the bot fixed it.

**Comment by NathanDuma** [comment]
I just tested this job and it was successful. Did you get a popup after applying to the job? If not, that is probably why the bot thought it failed.

**Comment by NathanDuma** [comment]
I tested this job out and I did not get an error.
