### ISSUE TITLE
Auto-Selects that I am not 18

### ISSUE THREAD

**Issue by zachlucas1** [NathanDuma/LinkedIn-Easy-Apply-Bot#14]
I started using this super cool program you made and one thing I noticed is that it auto-selects me as not being 18 years old on or before the start of the job. Just a small issue but it could potentially make me not qualified for any jobs it applies for. I could also be filling out the yaml file wrong but I am not sure. Let me know if this is a bug or a user error on my part!
<img width="514" alt="Screen Shot 2021-12-29 at 12 07 05 AM" src="https://user-images.githubusercontent.com/82626137/147636139-83e7701e-9697-416e-a157-792f985c73eb.png">

**Comment by NathanDuma** [comment]
Change line 350 in linkedeasyapplybot.py to be:
`elif len(radio_options) > 2`
Then it should answer yes to everything

**Comment by NathanDuma** [comment]
Change line 350/351 to this:
`
                    elif 'yes' in radio_options:
                        answer = 'yes'
                    else:
                        answer = radio_options[len(radio_options) - 1]
`
This will answer yes to everything.

**Comment by zachlucas1** [comment]
Awesome, I will try that. Thanks for the quick response!
