### ISSUE TITLE
Remote job

### ISSUE THREAD

**Issue by sumeetbandary** [NathanDuma/LinkedIn-Easy-Apply-Bot#16]
Can you add a parameter checkbox for are you willing for the remote job because it is selecting no by default?

**Comment by NathanDuma** [comment]
I don't believe this is a standard linkedin question, so the default answer would be the last option in the list. If you want to answer yes to everything, follow this: https://github.com/NathanDuma/LinkedIn-Easy-Apply-Bot/issues/14
