### ISSUE TITLE
Default Years of Experience Issue

### ISSUE THREAD

**Issue by zdondada** [NathanDuma/LinkedIn-Easy-Apply-Bot#19]
So, I'm someone with 20 years of experience and a super optimized resume. I usually get a response from 4/5 jobs I apply to. I figured if I scaled it up with this, I could land something epic. However, after applying to 200+ jobs, my response rate fell to 40/200 and I was baffled. 

Finally yesterday, I was watching the bot and I noticed for one of the "How many years of experience?" kind of questions that it went to, it entered "0." Immediately I was like "holy shit, that's why my resume isn't even getting looked at! It's putting "0" for a ton of them as they invariably ask these kinds of extra questions and I'm getting filtered out by ATS." Of course I'm super pissed at myself for not QA'ing the process better but I assumed if I have 15 as the default, it would either put 15 or NULL thus preventing the jobs from even successfully submitting, so how in the hell is it doing this? I went through the config and there's literally no "0" even in my entire TXT file. Can you please help me look into this? My car is about to get repossessed and I was trying to speed up my job search, but it actually slowed it down.

**Comment by zdondada** [comment]
PS C:\WINDOWS\system32> python main.p


====== WebDriver manager ======
Current google-chrome version is 97.0
Get LATEST chromedriver version for 9
Trying to download new driver from ht
Driver has been saved in cache [C:\Us
C:\WINDOWS\system32\main.py:16: Depre
  driver = webdriver.Chrome(ChromeDri

DevTools listening on ws://127.0.0.1:
[27228:20740:0204/180106.190:ERROR:de
ed to read descriptor from node conne
[27228:20740:0204/180106.191:ERROR:de
ed to read descriptor from node conne
[27228:20740:0204/180106.192:ERROR:de
ed to read descriptor from node conne
[27228:616:0204/180106.198:ERROR:chro
If you don't see the END: message, th
[27228:616:0204/180106.199:ERROR:chro
[27228:616:0204/180106.231:ERROR:chro
't see the END: message, this is crbu
[27228:616:0204/180107.153:ERROR:chro
Starting the search for Digital Marke
Going to job page 0
Starting the application process for
[24892:12988:0204/180254.465:ERROR:gp
Already applied to the job!
Applying to the job....
Traceback (most recent call last):
  File "C:\WINDOWS\system32\linkedine
    next_button.click()
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZDADDY\AppData\Local
y", line 80, in click
    self._execute(Command.CLICK_ELEME
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZDADDY\AppData\Local
y", line 633, in _execute
    return self._parent.execute(comma
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZDADDY\AppData\Local
", line 321, in execute
    self.error_handler.check_response
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZDADDY\AppData\Local
.py", line 242, in check_response
    raise exception_class(message, sc
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
selenium.common.exceptions.StaleEleme
the page document
  (Session info: chrome=97.0.4692.99)

Failed to apply to job! Please submit
Writing to the failed csv file...

**Comment by NathanDuma** [comment]
Could you send the job link? If you can't find it, it should be in your jobs tab on linkedin under applied.

**Comment by zdondada** [comment]
Thanks for the quick response. I can't tell which one it was so I'm just going to run the script again and grab it when it hits one - the listings in this space are super common to have those parameters so I should find one within a few minutes. Let me check!

**Comment by zdondada** [comment]
Here you go. The Amazon question it put "0" for.

https://www.linkedin.com/jobs/view/2906628185/?alternateChannel=search&refId=LfzFacTKmxWgkmSSAtQXSw%3D%3D&trackingId=R4eEoKdEaJmgtk1yLYfK7A%3D%3D

**Comment by NathanDuma** [comment]
It's not a linkedin standard question and it required a numeric answer. Change line 430 & 436 in linkedineasyapply.py to be max(self.technology_default, self.industry_default) instead of 0. This would probably fix the issue.

**Comment by zdondada** [comment]
Awesome I'll try it out thanks brother

**Comment by zdondada** [comment]
I'm testing right now.

I found another issue - if it asks "Are you OK with remote work?" it puts NO.

https://www.linkedin.com/jobs/view/2882999644/?eBP=JOB_SEARCH_ORGANIC&recommendedFlavor=ACTIVELY_HIRING_COMPANY&refId=MaXJW1AHbTRhrddnIHz9xA%3D%3D&trackingId=co%2BPnBR7PZnpG8zaecVpog%3D%3D&trk=flagship3_search_srp_jobs

**Comment by NathanDuma** [comment]
Hello,

Please see one of the closed issues where I give a solution on how ti
answer yes to every question.

**Comment by zdondada** [comment]
Sweet - I'm not super hip I just started using Python for this project.. when you say replace you mean make it say this:

  to_enter = max(self.technology_default, self.industry_default)
                        else:
                            to_enter = " ‏‏‎ "

                    if text_field_type == 'numeric':
                        if not isinstance(to_enter, (int, float)):
                            to_enter = max(self.technology_default, self.industry_default)

And that would be the totality of 430 thru 436

**Comment by zdondada** [comment]
![image](https://user-images.githubusercontent.com/82267077/153048732-6726cd17-5455-4620-8f57-379615529d51.png)

**Comment by zdondada** [comment]
Dude thank you SO MUCH! After making the fixes and running about 70 applications through it, I've been so inundated with requests today I can't keep up! I have companies like TED (TedTalks) hitting me up for Senior Marketing Director jobs priced at 180-200k .... You're the MAN!
