### ISSUE TITLE
Procedure on Linux

### ISSUE THREAD

**Issue by alecdromano** [NathanDuma/LinkedIn-Easy-Apply-Bot#20]
Hi, thanks for providing this. Have you tested it on Linux? I'm trying to run it on Lubuntu 20.04 but the bot is entering "d" in the search field and the location it selects appears to be random. I stop it before it gets too far, because it's trying to apply me to irrelevant jobs.

Here's some of the output if it helps.

`python3 main.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

====== WebDriver manager ======
Current google-chrome version is 98.0.4758
Get LATEST chromedriver version for 98.0.4758 google-chrome
Driver [/home/myname/.wdm/drivers/chromedriver/linux64/98.0.4758.80/chromedriver] found in cache
main.py:16: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=browser_options)
main.py:16: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=browser_options)
Starting the search for D in J.
Going to job page 0
Starting the application process for this page...
^CTraceback (most recent call last):
  File "/home/myname/LinkedIn-Easy-Apply-Bot/linkedineasyapply.py", line 125, in apply_jobs
    self.scroll_slow(job_results)
  File "/home/myname/LinkedIn-Easy-Apply-Bot/linkedineasyapply.py", line 678, in scroll_slow
    time.sleep(random.uniform(1.0, 2.6))
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myname/LinkedIn-Easy-Apply-Bot/linkedineasyapply.py", line 81, in start_applying
    self.apply_jobs(location)
  File "/home/myname/LinkedIn-Easy-Apply-Bot/linkedineasyapply.py", line 130, in apply_jobs
    raise Exception("No more jobs on this page")
Exception: No more jobs on this page
Sleeping for 879.7411160469055 seconds.
^CTraceback (most recent call last):
  File "main.py", line 128, in <module>
    bot.start_applying()
  File "/home/myname/LinkedIn-Easy-Apply-Bot/linkedineasyapply.py", line 101, in start_applying
    time.sleep(time_left)
KeyboardInterrupt
`

**Comment by NathanDuma** [comment]
There was a similar issue (see the closed ones) and I put the solution in
there. Let me know if this works for you.

**Comment by NathanDuma** [comment]
See https://github.com/NathanDuma/LinkedIn-Easy-Apply-Bot/issues/18
