### ISSUE TITLE
(Not an issue): Reducing default waiting time for next page

### ISSUE THREAD

**Issue by voidbydefault** [NathanDuma/LinkedIn-Easy-Apply-Bot#24]
Hi Nathan,

First, great job. I am using on Linux with my test LI account and not banned. 

Two questions:

1. How to reduce default waiting/sleep times? For example:

> Sleeping for 892.995133638382 seconds.
> Sleeping for 12.566666666666666 minutes.

Any tips? Plus any caveats/risks? 

2. Any instances of accounts being banned in your knowledge? Based on my testing so far, the way script works using Chrome, seems pretty much harmless so I don't see a reason of account being banned. 

Apologies to open this discussion as an issue because I couldn't find any other way to speak to you.

Thanks.

Edit: 3/15/22

For # 1, found:
> random.randint(500, 900)

In linkedineasyapply.py

Is there a reason for this interval? That is, is it more safer versus (250, 450)? Thanks.

**Comment by NathanDuma** [comment]
You can try less time but I personally have and it just ends up logging me out randomly after <10 pages. The sweet spot seems to be 15 minutes between pages.

**Comment by voidbydefault** [comment]
> You can try less time...
Thanks.
