### ISSUE TITLE
New questions in some LinkedIn Easy Apply jobs

### ISSUE THREAD

**Issue by voidbydefault** [NathanDuma/LinkedIn-Easy-Apply-Bot#28]
Hi,

Bot failed on some jobs, these were the questions. How can these be added to bot? I would attempt to send a pull request if I am successful.

Scrapped code from LI page is here:

**Form 1**
https://pastebin.com/ZxbJA04T

**Form 2**
https://pastebin.com/J6G0upVN

Thanks.

**Comment by NathanDuma** [comment]
Could you link these two jobs? They will be outputted in the failed file in the directory you specified in the config file.

**Comment by voidbydefault** [comment]
> Could you link these two jobs?

Job ID was there in the code I pasted, but here you go: https://www.linkedin.com/jobs/view/2988695263/

This has two additional forms which were scraped in HTML code in OP.

Thanks.

**Comment by docoined** [comment]
@NathanDuma This is a question for further clarification:

_____________
titleBlacklist:
 #- word1
 #- word2
_____________

I observed after including several blacklist keywords here i keep getting the below error:

_____________
Starting the application process for this page...
/Users/DO/Downloads/LinkedIn-Easy-Apply-Bot-master/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py:464: UserWarning: find_elements_by_class_name is deprecated. Please use find_elements(by=By.CLASS_NAME, value=name) instead
  warnings.warn("find_elements_by_class_name is deprecated. Please use find_elements(by=By.CLASS_NAME, value=name) instead")
/Users/DO/Downloads/LinkedIn-Easy-Apply-Bot-master/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py:446: UserWarning: find_element_by_class_name is deprecated. Please use find_element(by=By.CLASS_NAME, value=name) instead
  warnings.warn("find_element_by_class_name is deprecated. Please use find_element(by=By.CLASS_NAME, value=name) instead")
Job contains blacklisted keyword or company name!
Traceback (most recent call last):
  File "/Users/DO/Downloads/LinkedIn-Easy-Apply-Bot-master/linkedineasyapply.py", line 81, in start_applying
    self.apply_jobs(location)
  File "/Users/DO/Downloads/LinkedIn-Easy-Apply-Bot-master/linkedineasyapply.py", line 160, in apply_jobs
    if word.lower() in job_title_parsed:
AttributeError: 'NoneType' object has no attribute 'lower'
Sleeping for 1103.148691892624 seconds.
__________________________________________




My Question:
Is the blacklist keywords affecting the title or all the text on the job page?

BTW, it works working fine, just the above error. 

Thanks for your time.

**Comment by NathanDuma** [comment]
Could you post your blacklist? Did you miss the dashes or have a random
dash somewhere?

**Comment by voidbydefault** [comment]
> @NathanDuma This is a question for further clarification:
> ...is deprecated...

You can ignore 'deprecated' warnings. 

> Job contains blacklisted keyword or company name! 

Based on my experience so far, keywords affect entire job post including heading/body text. 

> Netiquette

Lastly, your issue is different than the OP of this thread. Netiquette is to open a separate thread instead of posting off topic content in threads created by others (i.e. avoid thread hijacking).

**Comment by voidbydefault** [comment]
> Job ID was there in the code I pasted, but here you go: https://www.linkedin.com/jobs/view/2988695263/

Hi @NathanDuma 
If you had time to look into this, please advise best way to add additional forms/questions. I had a surface level look, it seems we need to add these questions in 'main.py'. Thanks.

**Comment by voidbydefault** [comment]
Seems dev is not interested. Closing.
