### ISSUE TITLE
Uploading photo error, uploads CV instead. Freezes the application completely! Roadblock! 

### ISSUE THREAD

**Issue by amishjha** [NathanDuma/LinkedIn-Easy-Apply-Bot#4]
![image](https://user-images.githubusercontent.com/51803186/120909100-1501e200-c68f-11eb-85d1-466ee261487e.png)

Either:
A. Include file path for pic 

OR 

B. Do not insert cv.pdf into photo coz it is not mandatory. (in fact if you do not insert anything in the photo it will continue as normal)

This completely freezes the bot. The action pauses however when I remove the wrongly uploaded file by clicking cross icon and clicking next. it resumes. So i guess only for this photo upload section you can add an exception.?

**Comment by NathanDuma** [comment]
In linkedineasyapply.py remove both of these lines: 594 and 595 and restart the bot. Feel free to make a PR and I can review it.

**Comment by amishjha** [comment]
sure ok, il little noob to all this, il try my best to make a PR. Meanwhile I have a similar code to be made for a platform, but very simple (just 2 buttons clicks needed). Let me know if you would be available to design it, I can give you a brief over email.

**Comment by NathanDuma** [comment]
I have pushed the changes and this issue should no longer persist. Please pull.
