### ISSUE TITLE
linkedineasyapply.py", line 81, in start_applying     self.apply_jobs(location)

### ISSUE THREAD

**Issue by logix727** [NathanDuma/LinkedIn-Easy-Apply-Bot#43]

**Comment by balayokesh** [comment]
You have to replace the placeholder text at line number 37 of `config.yaml` file with your preferred job location
![image](https://user-images.githubusercontent.com/59578892/185764867-a755c8eb-1bf9-49ba-9e95-4ca456b747e6.png)
