### ISSUE TITLE
bot keeps applying for jobs in far off lands....

### ISSUE THREAD

**Issue by secretgrampuh** [NathanDuma/LinkedIn-Easy-Apply-Bot#44]
edit: Ignore me, i've never used a .yaml file before and didn't realize I needed dashes. I'll leave this up in case anyone else has the same formatting issues. The solution is, when filling out .yaml, you must format like this:

positions:
 - Adobe Premiere
 - Avid Media Composer
 - animatic

~~~~Below is my original post~~~~

Hey, first off, you're a total ledge for writing this. Once i got it all set up I ran it and noticed it had little random slow scrolls and wait times... nice.

However, i do have an issue! It does seem to be getting my "job title" and "location" correct, see attached screencap below. Job 
title is always a single letter "i" "m" "v" or something, and location is always a different country. Am I doing something wrong? Is that just how the bot... looks? The jobs are at least sort of in my space (video/media) but that could be just because of my linkedin profile and resume.

When i filled out the config.yaml I just write directly under "positions", just plain text no formatting... does it need to be in quotes? Wondering if this is a string issue and somehow it's just pulling random letters from the positions area?? The location is also "E, Savannakhet, Laos" so maybe it's grabbing a random "i" and "e" and just searching it?

my config.yaml looks like this:

positions:
 Adobe Premiere
 Avid Media Composer
 animatic

locations:
 United States

Any thoughts would be appreciated. thanks!

<img width="500" alt="Screen Shot 2022-08-06 at 9 37 09 PM" src="https://user-images.githubusercontent.com/85971387/183275567-d2a7d0fe-7020-44f2-bc7b-8fff4b64022c.png">

**Comment by secretgrampuh** [comment]
So It's definitely parsing my strings weird somehow... my two positions were "Adobe Premiere" and "Avid Media Composer", and somehow it searched "i" "e" and then on the next search it ran "o" and "s" in the job/location texts... Both look like index -3 and -4 in my positions strings.

So I don't know why it's parsing them funny, if you have any ideas let me know. I'll look more at the code in the morning. Great job on the bot though!

**Comment by NathanDuma** [comment]
Are you still having this issue? Can you post the config file? Don't
include your password.

**Comment by secretgrampuh** [comment]
No I figured out this particular issue was just the way I was formatting my strings in the .yaml file. I didn't start each newline with "space - space"

I do have a separate question for you:

Could you please show how to add a new parameter? Several of the jobs I'm applying for have parameters such as "salary", sometimes with line of text field, sometimes with drop down choices.

Adding a new parameter for text field seems straightforward since you've already done so many of those: location, job title, languages, degrees, etc.

In my case one of the more popular employers has a prompt "language: " (text line), followed by drop down with the same 4 or 5 choices. Currently the bot just skips it and it's probably done it on 30-50 applications, same text field every time.

Could you put together something to show us where to change code in order to create custom parameters? Even just text field would probably be helpful.
