### ISSUE TITLE
Bot Just Doesn't Work

### ISSUE THREAD

**Issue by GNLaForgia-Bruner** [NathanDuma/LinkedIn-Easy-Apply-Bot#60]
![image](https://user-images.githubusercontent.com/93950533/200199099-14454867-10d5-4c8e-891a-0273165d9cc9.png)

Any help?

**Comment by NathanDuma** [comment]
Please read the readme to setup the config file.

**Comment by GNLaForgia-Bruner** [comment]
Figured it out right as your responded. Thanks @NathanDuma
