### ISSUE TITLE
sleep duration is too long

### ISSUE THREAD

**Issue by Sy3Omda** [NathanDuma/LinkedIn-Easy-Apply-Bot#7]
`
Sleeping for 881.592579126358 seconds.
`
could we minimize this sleeping time , i believe this is 14 min!!
could this be between 5 to 7 min as maximum .

one more thing i get this error after this sleeping time 
`[9640:4564:0718/145744.396:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled`

OS : Windows 10
python version : 3.9.6
running the script from Powershell

**Comment by NathanDuma** [comment]
In linkedineasyapply.py line 64, change 15 to however many minutes you want it to sleep for. I have personally tried less time and it ends up logging me out, but feel free to try to see if there is a lesser time that works.
For the second issue, does it stop applying to jobs hwen you see this? This isn't an issue related to my bot and I haven't seen it, but a quick google search seems that this is an issue with the chromedriver and using a virtual machine.

**Comment by EdwardOak** [comment]
Here's what my thing's doing:

13:55:25 - INFO - 596.0 minutes left in this search
13:55:25 - DEBUG - Sleeping for 4.6
13:56:13 - INFO - Lock avoided.
13:56:33 - INFO - 595.0 minutes left in this search
13:56:33 - DEBUG - Sleeping for 3.5
13:57:03 - INFO - 595.0 minutes left in this search
13:57:03 - DEBUG - Sleeping for 4.8
13:57:30 - INFO - 594.0 minutes left in this search
13:57:30 - DEBUG - Sleeping for 4.8
13:57:57 - INFO - 594.0 minutes left in this search
13:57:57 - DEBUG - Sleeping for 4.0
13:58:23 - INFO - 593.0 minutes left in this search
13:58:23 - DEBUG - Sleeping for 4.1
13:58:50 - INFO - 593.0 minutes left in this search
13:58:50 - DEBUG - Sleeping for 4.7
13:59:17 - INFO - 592.0 minutes left in this search
13:59:17 - DEBUG - Sleeping for 4.8
13:59:44 - INFO - 592.0 minutes left in this search
13:59:44 - DEBUG - Sleeping for 3.6
14:00:09 - INFO - 591.0 minutes left in this search
14:00:09 - DEBUG - Sleeping for 4.9

**Comment by NathanDuma** [comment]
You are not using my bot, but someone else's.

**Comment by EdwardOak** [comment]
@NathanDuma if you're talking to me, no, I am using your bot (which is AMAZING btw).
But yeah, it loops sometimes, gotta reset it, clunky at times. Any idea?

**Comment by EdwardOak** [comment]
Right now and for the past 10 tries. It starts, does 1 or two applications, then promptly goes to next job (abandonning 1st job) and then it stalls on page 2. looping debug

**Comment by EdwardOak** [comment]
My error. I'll try yours
