### ISSUE TITLE
Default to 0 even if i both of them to 5

### ISSUE THREAD

**Issue by nicolaieg** [NathanDuma/LinkedIn-Easy-Apply-Bot#8]
Hello, 
I setted the default value to 5, but to some questions ie Social Media Marketing it sets automatically to 0. Do u have any idea what I can do to set the default on all values?

**Comment by nicolaieg** [comment]
I saw that you have only some specific text, can I add different variants through coma? Or can u set the default for all queries?
 to_enter = ''
                    if 'experience do you currently have' in question_text:
                        no_of_years = self.industry_default

                        for industry in self.industry:
                            if industry.lower() in question_text:
                                no_of_years = self.industry[industry]
                                break

                        to_enter = no_of_years
                    elif 'many years of work experience do you have using' in question_text:
                        no_of_years = self.technology_default

**Comment by NathanDuma** [comment]
There are two default values, did you set both? If you did, then it is probably because the linkedin question is not the standard one.

**Comment by iamrhyot** [comment]
Seems a lot of apps are using nonstandard formats for the queries
